<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>assets\app.ico</ApplicationIcon>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="assets\app.ico" />
    <Content Include="assets\characters\**\*.gif" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="assets\characters\**\*.ico" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
